# src/beautyspot/core.py

import asyncio
import hashlib
import logging
import functools
import inspect
import warnings
import weakref
from concurrent.futures import ThreadPoolExecutor, Executor, wait
from pathlib import Path
from typing import (
    Any,
    Callable,
    Optional,
    Union,
    Type,
    overload,
    TypeVar,
    TypedDict,
    Generic,
    TypeVarTuple,
    Unpack,
    ParamSpec,
)

from beautyspot.limiter import TokenBucket
from beautyspot.storage import BlobStorageBase
from beautyspot.db import TaskDB
from beautyspot.serializer import MsgpackSerializer, SerializationError, SerializerProtocol
from beautyspot.cachekey import KeyGen, KeyGenPolicy

# ジェネリクスの定義
P = ParamSpec("P")
R = TypeVar("R")
T = TypeVar("T")
Ts = TypeVarTuple("Ts")

logger = logging.getLogger(__name__)
logger.addHandler(logging.NullHandler())


# --- キャッシュミスを表す番兵オブジェクト ---
CACHE_MISS = object()


class ScopedMark(Generic[R]):
    """
    Helper context manager for 'with spot.cached_run(...):'.
    Enforces that the cached function can only be called within the block.
    """

    def __init__(self, spot: "Spot", funcs: tuple[Callable, ...], **options):
        self.spot = spot
        self.funcs = funcs
        self.options = options
        self._is_active = False  # コンテキストの状態管理フラグ

    def __enter__(self) -> R:
        self._is_active = True

        def make_scoped_guard(func):
            # 1. 既存のロジックでキャッシュ機能付きラッパーを作成
            cached_func = self.spot.mark(func, **self.options)

            # 2. Async/Sync に合わせてガード処理をラップ
            if inspect.iscoroutinefunction(func):

                @functools.wraps(cached_func)
                async def _async_guard(*args, **kwargs):
                    if not self._is_active:
                        # 明確なエラーメッセージで誤用を通知
                        raise RuntimeError(
                            f"The cached function '{func.__name__}' was called outside of its 'cached_run' context. "
                            "Cached functions generated by 'cached_run' are only valid within the 'with' block."
                        )
                    return await cached_func(*args, **kwargs)

                return _async_guard
            else:

                @functools.wraps(cached_func)
                def _sync_guard(*args, **kwargs):
                    if not self._is_active:
                        raise RuntimeError(
                            f"The cached function '{func.__name__}' was called outside of its 'cached_run' context. "
                            "Cached functions generated by 'cached_run' are only valid within the 'with' block."
                        )
                    return cached_func(*args, **kwargs)

                return _sync_guard

        # 全ての関数にガードを適用
        wrappers = [make_scoped_guard(f) for f in self.funcs]

        # 実行時の戻り値制御（型定義と実装の辻褄合わせ）
        if len(wrappers) == 1:
            return wrappers[0]  # type: ignore
        return tuple(wrappers)  # type: ignore

    def __exit__(self, exc_type, exc_val, exc_tb):
        # コンテキスト終了時にフラグを下ろす
        self._is_active = False


class SpotOptions(TypedDict, total=False):
    """
    Spotのオプション引数を定義する。
    """
    blob_warning_threshold: int
    default_save_blob: bool
    default_version: str | None
    default_content_type: str | None
    tpm: int
    io_workers: int
    executor: Executor | None
    defalut_wait: bool


class Spot:
    """
    Spot class that handles task management, serialization, and
    resource management for marked functions including caching and storage.
    """
    def __init__(
        self,
        name: str,
        # 必須の依存オブジェクト (DI)
        db: TaskDB,
        serializer: SerializerProtocol,
        storage: BlobStorageBase,
        
        # オプション設定
        tpm: int = 10000,
        io_workers: int = 4,
        blob_warning_threshold: int = 1024 * 1024,
        executor: Optional[Executor] = None,
        
        # デフォルト動作設定
        default_save_blob: bool = False,
        default_version: Optional[str] = None,
        default_content_type: Optional[str] = None,
        default_wait: bool = True,
        
        **kwargs: Any,
    ) -> None:
        self.name = name
        
        # --- 依存オブジェクトの注入 ---
        self.db = db
        self.serializer = serializer
        self.storage = storage

        # --- オプション設定の適用 ---
        self.blob_warning_threshold = blob_warning_threshold
        self.default_save_blob = default_save_blob
        self.default_version = default_version
        self.default_content_type = default_content_type
        self.default_wait = default_wait

        # --- ワークスペースとDBの初期化 ---
        self.workspace_dir = Path(".beautyspot")
        self._setup_workspace()
        self.db.init_schema()

        # --- レートリミッター ---
        self.bucket = TokenBucket(tpm)

        # --- Executor管理 ---
        if executor is not None:
            self.executor = executor
            self._own_executor = False
        else:
            self.executor = ThreadPoolExecutor(max_workers=io_workers)
            self._own_executor = True
            # GC時の安全なシャットダウン
            self._finalizer = weakref.finalize(self, self._shutdown_executor, self.executor)

        # 実行中のタスクを管理するセット
        self._active_futures = set()

    def _track_future(self, future: Any):
        """Futureを追跡セットに加え、完了したら削除する"""
        self._active_futures.add(future)
        future.add_done_callback(self._active_futures.discard)

    def _setup_workspace(self):
        """Ensure the workspace directory and .gitignore exist."""
        if not self.workspace_dir.exists():
            self.workspace_dir.mkdir(parents=True, exist_ok=True)

        gitignore_path = self.workspace_dir / ".gitignore"
        if not gitignore_path.exists():
            with open(gitignore_path, "w") as f:
                f.write("*\n")

    @staticmethod
    def _shutdown_executor(executor: Executor):
        executor.shutdown(wait=True)

    def shutdown(self, wait: bool = True):
        if self._own_executor and self._finalizer.alive:
            self._finalizer()

    def __enter__(self) -> "Spot":
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        """
        コンテキストを抜ける際の処理。
        Executorは停止させず、現在実行中のバックグラウンドタスクの完了だけを待つ。
        これにより、同じSpotインスタンスを別の with ブロックで再利用可能にする。
        """
        if self._active_futures:
            # アクティブなFutureのリストを作成して完了を待機
            # concurrent.futures.wait を使用
            wait(list(self._active_futures))

    def _resolve_key_fn(
        self,
        func: Callable,
        keygen: Optional[Union[Callable, KeyGenPolicy]] = None,
        input_key_fn: Optional[Union[Callable, KeyGenPolicy]] = None,
    ) -> Optional[Callable]:
        if keygen is not None and input_key_fn is not None:
            raise ValueError(
                "Cannot specify both 'keygen' and 'input_key_fn'. Please use 'keygen'."
            )

        target = keygen

        if input_key_fn is not None:
            warnings.warn(
                "The 'input_key_fn' argument is deprecated and will be removed in v3.0. "
                "Please use 'keygen' instead.",
                DeprecationWarning,
                stacklevel=3,
            )
            target = input_key_fn

        if isinstance(target, KeyGenPolicy):
            return target.bind(func)
        
        return target

    def register(
        self,
        code: int,
        encoder: Callable[[T], Any],
        decoder: Optional[Callable[[Any], T]] = None,
        decoder_factory: Optional[Callable[[Type[T]], Callable[[Any], T]]] = None,
    ) -> Callable[[Type[T]], Type[T]]:
        if decoder is None and decoder_factory is None:
            raise ValueError("Must provide either `decoder` or `decoder_factory`.")

        def decorator(cls: Type) -> Type:
            actual_decoder = decoder
            if decoder_factory:
                actual_decoder = decoder_factory(cls)

            if actual_decoder is None:
                raise ValueError("Decoder resolution failed.")

            self.register_type(cls, code, encoder, actual_decoder)
            return cls

        return decorator

    def register_type(
        self,
        type_class: Type[T],
        code: int,
        encoder: Callable[[T], Any],
        decoder: Callable[[Any], T],
    ):
        if isinstance(self.serializer, MsgpackSerializer):
            self.serializer.register(type_class, code, encoder, decoder)
        else:
            raise NotImplementedError(
                f"The current serializer '{type(self.serializer).__name__}' does not support type registration.\n"
                "The `@spot.register` decorator is only compatible with the default MsgpackSerializer."
            )

    # --- Core Logic (Sync) ---

    def _resolve_settings(
        self, save_blob: bool | None, version: str | None, content_type: str | None
    ) -> tuple[bool, str | None, str | None]:
        final_save_blob = save_blob if save_blob is not None else self.default_save_blob
        final_version = version if version is not None else self.default_version
        final_content_type = (
            content_type if content_type is not None else self.default_content_type
        )
        return final_save_blob, final_version, final_content_type

    def _make_cache_key(
        self,
        func_name: str,
        args: tuple,
        kwargs: dict,
        input_key_fn: Optional[Callable],
        version: str | None,
    ) -> tuple[str, str]:
        iid = (
            input_key_fn(*args, **kwargs)
            if input_key_fn
            else KeyGen._default(args, kwargs)
        )

        key_source = f"{func_name}:{iid}"
        if version:
            key_source += f":{version}"

        ck = hashlib.md5(key_source.encode()).hexdigest()
        return iid, ck

    def _execute_sync(
        self,
        func: Callable,
        args: tuple,
        kwargs: dict,
        save_blob: bool | None,
        input_key_fn: Optional[Union[Callable, KeyGenPolicy]],
        version: str | None,
        content_type: Optional[str],
        serializer: Optional[SerializerProtocol],
        wait: bool,
    ) -> Any:
        # Resolve Defaults
        s_blob, s_ver, s_ct = self._resolve_settings(save_blob, version, content_type)
        effective_key_fn = self._resolve_key_fn(func, keygen=None, input_key_fn=input_key_fn)

        iid, ck = self._make_cache_key(
            func.__name__, args, kwargs, effective_key_fn, s_ver
        )

        # 1. Check Cache
        cached = self._check_cache_sync(ck, serializer)
        if cached is not CACHE_MISS:
            return cached

        # 2. Execute
        res = func(*args, **kwargs)

        # 3. Save
        save_args = (ck, func.__name__, str(iid), s_ver, res, s_ct, s_blob, serializer)
        if wait:
            self._save_result_sync(*save_args)
        else:
            self.executor.submit(self._save_result_safe, *save_args)

        return res

    async def _execute_async(
        self,
        func: Callable,
        args: tuple,
        kwargs: dict,
        save_blob: bool | None,
        input_key_fn: Optional[Union[Callable, KeyGenPolicy]],
        version: str | None,
        content_type: Optional[str],
        serializer: Optional[SerializerProtocol],
        wait: bool,
    ) -> Any:
        # Resolve Defaults
        s_blob, s_ver, s_ct = self._resolve_settings(save_blob, version, content_type)
        effective_key_fn = self._resolve_key_fn(func, keygen=None, input_key_fn=input_key_fn)

        iid, ck = self._make_cache_key(
            func.__name__, args, kwargs, effective_key_fn, s_ver
        )
        loop = asyncio.get_running_loop()

        # 1. Check Cache (Offload IO)
        cached = await loop.run_in_executor(self.executor, self._check_cache_sync, ck, serializer)
        if cached is not CACHE_MISS:
            return cached

        # 2. Execute (Async)
        res = await func(*args, **kwargs)

        # 3. Save (Offload IO)
        save_args = (ck, func.__name__, str(iid), s_ver, res, s_ct, s_blob, serializer)

        if wait:
            # 完了を待つ (awaitする)
            await loop.run_in_executor(self.executor, self._save_result_sync, *save_args)
        else:
            # 完了を待たない (awaitしない)
            # run_in_executor は Future を返すが、それを無視することでバックグラウンド実行となる
            # ただし例外ハンドリングのため _save_result_safe を使う
            loop.run_in_executor(self.executor, self._save_result_safe, *save_args)

        return res

    def _check_cache_sync(self, cache_key: str, serializer: Optional[SerializerProtocol] = None) -> Any:
        use_serializer = serializer or self.serializer

        entry = self.db.get(cache_key)

        if entry:
            r_type = entry["result_type"]
            r_val = entry["result_value"]
            r_data = entry.get("result_data")

            # Case 1: Native SQLite BLOB
            if r_type == "DIRECT_BLOB":
                if r_data is None:
                    return CACHE_MISS
                try:
                    return use_serializer.loads(r_data)
                except Exception as e:
                    logger.error(
                        f"Failed to deserialize DIRECT_BLOB for `{cache_key}`: {e}"
                    )
                    return CACHE_MISS

            # Case 2: External Blob
            elif r_type == "FILE":
                if r_val is None:
                    logger.warning(f"Data corruption: 'FILE' type record has no path for key `{cache_key}`")
                    return CACHE_MISS
                try:
                    data_bytes = self.storage.load(r_val)
                    return use_serializer.loads(data_bytes)
                except Exception:
                    return CACHE_MISS

        return CACHE_MISS

    # --- 安全なバックグラウンド実行用ラッパー ---
    def _save_result_safe(self, *args, **kwargs):
        """
        Wrapper for _save_result_sync to handle exceptions in background threads.
        """
        try:
            self._save_result_sync(*args, **kwargs)
        except Exception as e:
            # バックグラウンドでの失敗はメイン処理を止めないようログ出力に留める
            func_name = args[1] if len(args) > 1 else "unknown"
            logger.error(
                f"Background save failed for task '{func_name}': {e}", 
                exc_info=True
            )

    def _save_result_sync(
        self,
        cache_key: str,
        func_name: str,
        input_id: str,
        version: str | None,
        result: Any,
        content_type: str | None,
        save_blob: bool,
        serializer: Optional[SerializerProtocol] = None,
    ):
        use_serializer = serializer or self.serializer

        try:
            data_bytes = use_serializer.dumps(result)
        except SerializationError as e:
            raise e

        r_val = None
        r_blob = None
        r_type = "DIRECT_BLOB"

        if save_blob:
            r_val = self.storage.save(cache_key, data_bytes)
            r_type = "FILE"
        else:
            data_size = len(data_bytes)
            if data_size > self.blob_warning_threshold:
                logger.warning(
                    f"⚠️ Large data detected ({data_size / 1024:.1f} KB) for task '{func_name}'. "
                    f"Consider adding `@spot.mark(save_blob=True)`."
                )

            r_blob = data_bytes
            r_type = "DIRECT_BLOB"

        self.db.save(
            cache_key=cache_key,
            func_name=func_name,
            input_id=input_id,
            version=version,
            result_type=r_type,
            content_type=content_type,
            result_value=r_val,
            result_data=r_blob,
        )

    def limiter(self, cost: Union[int, Callable] = 1):
        def decorator(func):
            is_async = inspect.iscoroutinefunction(func)

            @functools.wraps(func)
            def sync_wrapper(*args, **kwargs):
                c = cost(*args, **kwargs) if callable(cost) else cost
                self.bucket.consume(c)
                return func(*args, **kwargs)

            @functools.wraps(func)
            async def async_wrapper(*args, **kwargs):
                c = cost(*args, **kwargs) if callable(cost) else cost
                await self.bucket.consume_async(c)
                return await func(*args, **kwargs)

            return async_wrapper if is_async else sync_wrapper

        return decorator

    @overload
    def mark(self, _func: Callable[P, R]) -> Callable[P, R]: ...

    @overload
    def mark(
        self,
        *,
        save_blob: Optional[bool] = None,
        keygen: Optional[Union[Callable, KeyGenPolicy]] = None,
        input_key_fn: Optional[Union[Callable, KeyGenPolicy]] = None,
        version: str | None = None,
        content_type: Optional[str] = None,
        serializer: Optional[SerializerProtocol] = None,
        wait: Optional[bool] = None,
    ) -> Callable[[Callable[P, R]], Callable[P, R]]: ...

    def mark(
        self,
        _func: Optional[Callable] = None,
        *,
        save_blob: Optional[bool] = None,
        keygen: Optional[Union[Callable, KeyGenPolicy]] = None,
        input_key_fn: Optional[Union[Callable, KeyGenPolicy]] = None,
        version: str | None = None,
        content_type: Optional[str] = None,
        serializer: Optional[SerializerProtocol] = None,
        wait: Optional[bool] = None,
    ) -> Any:
        if save_blob is None:
            save_blob = self.default_save_blob
        if version is None:
            version = self.default_version
        if content_type is None:
            content_type = self.default_content_type
        if wait is None:
            wait = self.default_wait

        def decorator(func):
            is_async = inspect.iscoroutinefunction(func)
            effective_key_fn = self._resolve_key_fn(func, keygen, input_key_fn)

            def make_key(args, kwargs):
                from .cachekey import KeyGen
                iid = (
                    effective_key_fn(*args, **kwargs)
                    if effective_key_fn
                    else KeyGen._default(args, kwargs)
                )
                key_source = f"{func.__name__}:{iid}"
                if version:
                    key_source += f":{version}"
                ck = hashlib.md5(key_source.encode()).hexdigest()
                return iid, ck

            @functools.wraps(func)
            def sync_wrapper(*args, **kwargs):
                iid, ck = make_key(args, kwargs)
                cached = self._check_cache_sync(ck, serializer)
                if cached is not CACHE_MISS:
                    return cached
                res = func(*args, **kwargs)
                save_args = (
                    ck,
                    func.__name__,
                    str(iid),
                    version,
                    res,
                    content_type,
                    save_blob,
                    serializer,
                )
                if wait:
                    self._save_result_sync(*save_args)
                else:
                    future = self.executor.submit(self._save_result_safe, *save_args)
                    self._track_future(future)
                return res

            @functools.wraps(func)
            async def async_wrapper(*args, **kwargs):
                iid, ck = make_key(args, kwargs)
                loop = asyncio.get_running_loop()
                cached = await loop.run_in_executor(
                    self.executor, self._check_cache_sync, ck, serializer
                )
                if cached is not CACHE_MISS:
                    return cached
                res = await func(*args, **kwargs)
                save_args = (
                    ck,
                    func.__name__,
                    str(iid),
                    version,
                    res,
                    content_type,
                    save_blob,
                    serializer,
                )
                if wait:
                    await loop.run_in_executor(self.executor, self._save_result_sync, *save_args)
                else:
                    future = self.executor.submit(self._save_result_safe, *save_args)
                    self._track_future(future)

                return res

            return async_wrapper if is_async else sync_wrapper

        if _func is not None and callable(_func):
            return decorator(_func)
        return decorator

    @overload
    def cached_run(
        self,
        func: T,
        /,
        *,
        save_blob: Optional[bool] = None,
        keygen: Optional[Union[Callable, KeyGenPolicy]] = None,
        input_key_fn: Optional[Union[Callable, KeyGenPolicy]] = None,
        version: str | None = None,
        content_type: Optional[str] = None,
        serializer: Optional[SerializerProtocol] = None,
    ) -> ScopedMark[T]: ...

    @overload
    def cached_run(
        self,
        *funcs: Unpack[Ts],
        save_blob: Optional[bool] = None,
        keygen: Optional[Union[Callable, KeyGenPolicy]] = None,
        input_key_fn: Optional[Union[Callable, KeyGenPolicy]] = None,
        version: str | None = None,
        content_type: Optional[str] = None,
        serializer: Optional[SerializerProtocol] = None,
    ) -> ScopedMark[tuple[Unpack[Ts]]]: ...

    def cached_run(
        self,
        *funcs: Any,
        save_blob: Optional[bool] = None,
        keygen: Optional[Union[Callable, KeyGenPolicy]] = None,
        input_key_fn: Optional[Union[Callable, KeyGenPolicy]] = None,
        version: str | None = None,
        content_type: Optional[str] = None,
        serializer: Optional[SerializerProtocol] = None,
    ):
        if not funcs:
            raise ValueError("At least one function must be provided to cached_run.")

        for f in funcs:
            if not callable(f):
                raise TypeError(
                    f"All arguments to cached_run must be callable. Got: {type(f)}"
                )

        return ScopedMark(
            self,
            funcs,
            save_blob=save_blob,
            keygen=keygen,
            input_key_fn=input_key_fn,
            version=version,
            content_type=content_type,
            serializer=serializer,
        )

